version: "3.5"
services:
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: on-failure
    volumes:
      - redisdata:/data

  stunnel:
    image: "goelze/stunnel"
    ports:
      - "6380:6380"
    volumes:
      - ./stunnel:/etc/stunnel/

volumes:
  redisdata: